# Generated by Django 4.1.3 on 2022-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=50, null=True)),
                ('option_type', models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], max_length=10)),
                ('strike_price', models.FloatField(null=True)),
                ('last_price', models.FloatField(null=True)),
                ('price_change', models.FloatField(null=True)),
                ('price_change_perc', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('option_value', models.FloatField(default=0.0)),
                ('open_interest', models.FloatField(null=True)),
                ('open_interest_change', models.FloatField(null=True)),
                ('open_interest_change_perc', models.FloatField(null=True)),
                ('stock_position', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
